export const types = Object.freeze({
    // Sync
    STARSHIPS_START_FETCHING: 'STARSHIPS_START_FETCHING',
    STARSHIPS_STOP_FETCHING: 'STARSHIPS_STOP_FETCHING',
    STARSHIPS_FILL: 'STARSHIPS_FILL',
    // Async
    STARSHIPS_FETCH_ASYNC: 'STARSHIPS_FETCH_ASYNC'
});